# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2c80877fb5f926c1e3a0745e87e87cafa766542dfca631610ee80dd6620ba68412c58aece11c0c4da55271ca2fcb24d52ba25b266efe8b19b5e163142477ae3

test:
  secret_key_base: 73019388c2519941ba803f386c172e9c51bab119df6846a217c4ee3af24048bd08e15695ba68b8073d3ef75320f60f4c71fe530ee739aa0edddc93af384d55ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
